server:
  port: 8081

spring:
  datasource:
    username: root
    password: cc123456
    url: jdbc:mysql://47.98.135.4/wx_database?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&autoReconnect=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
